#!/bin/sh

echo "🛡️  [Pre-Push] Running Pint Linter & Pest Tests..."

composer ci
if [ $? -ne 0 ]; then
    echo "❌ Composer tests check failed!"
    exit 1
fi

echo "✅ All pre-push checks passed successfully!"
exit 0
