<?php

declare(strict_types=1);

beforeEach(function () {
    authenticateAsAdmin();
    \SiteForgeAI\Core\Router::register();
});

test('it seeds site via POST /seeder/seed and removes mock data via POST /seeder/remove-mock', function () {
    $request = new WP_REST_Request('POST', '/siteforge_ai/v1/seeder/seed');
    $request->set_header('content-type', 'application/json');
    $request->set_body(json_encode([
        'site' => [
            'title'   => 'Seeded Website Title',
            'tagline' => 'Generated by SiteForge AI',
        ],
        'pages' => [
            [
                'title'         => 'Home',
                'slug'          => 'seeded-home',
                'is_front_page' => true,
                'sections'      => [
                    ['type' => 'hero', 'heading' => 'Hero Heading', 'content' => 'Hero text'],
                ],
            ],
            [
                'title'         => 'Contact Us',
                'slug'          => 'seeded-contact',
                'is_front_page' => false,
                'sections'      => [
                    ['type' => 'contact_info', 'heading' => 'Contact Heading', 'content' => 'Contact details'],
                ],
            ],
        ],
        'posts' => [
            [
                'title'   => 'First Seeded Post',
                'slug'    => 'first-seeded-post',
                'content' => 'Seeded post body.',
            ],
        ],
    ]));

    $response = rest_do_request($request);
    expect($response->get_status())->toBe(200);

    $data = $response->get_data();
    expect($data['ok'])->toBeTrue()
        ->and($data['data'])->toHaveKeys(['batch_id', 'pages', 'posts']);

    $batchId = $data['data']['batch_id'];

    // Test POST /seeder/remove-mock
    $removeRequest = new WP_REST_Request('POST', '/siteforge_ai/v1/seeder/remove-mock');
    $removeRequest->set_header('content-type', 'application/json');
    $removeRequest->set_body(json_encode([
        'batch_id' => $batchId,
    ]));

    $removeResponse = rest_do_request($removeRequest);
    expect($removeResponse->get_status())->toBe(200);

    $removeData = $removeResponse->get_data();
    expect($removeData['ok'])->toBeTrue()
        ->and($removeData['data']['pages_deleted'])->toBeGreaterThanOrEqual(2)
        ->and($removeData['data']['posts_deleted'])->toBeGreaterThanOrEqual(1);
});
